"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { brandPoliceService } from "../lib/brand-police-service";

const navigation = [
  ["Overview", "overview"],
  ["Findings", "findings", 3],
  ["Scans", "scans"],
  ["Upload check", "upload"],
  ["Assets", "assets"],
  ["Domains", "domains"],
  ["Rules", "rules"],
  ["Reports", "reports"],
];

const domainsSeed = [
  { domain:"brandyhq.com", type:"Owned", status:"Monitoring", frequency:"Daily", pages:148, findings:0, score:100 },
  { domain:"seahawkmedia.com", type:"Approved partner", status:"Monitoring", frequency:"Weekly", pages:42, findings:1, score:96 },
  { domain:"brandfetch.com", type:"Unknown", status:"Monitoring", frequency:"Weekly", pages:18, findings:1, score:71 },
  { domain:"saasframe.io", type:"Unknown", status:"Monitoring", frequency:"Weekly", pages:9, findings:1, score:68 },
];

const rulesSeed = [
  { id:1, title:"Current logo only", description:"Flag retired or unapproved logo versions", category:"Logo", severity:"High", enabled:true },
  { id:2, title:"Protect logo proportions", description:"Detect stretched, compressed, cropped, or rotated logos", category:"Logo", severity:"High", enabled:true },
  { id:3, title:"Approved brand colors", description:"Flag recolored marks outside approved variants", category:"Color", severity:"Medium", enabled:true },
  { id:4, title:"Minimum clear space", description:"Check spacing around the primary logo and symbol", category:"Layout", severity:"Medium", enabled:true },
  { id:5, title:"Minimum asset resolution", description:"Flag blurry assets below 240 px wide", category:"Quality", severity:"Low", enabled:false },
  { id:6, title:"Approved terminology", description:"Detect prohibited product names and retired messaging", category:"Voice", severity:"Medium", enabled:false },
];

const assetsSeed = [
  { name:"Primary logo", type:"Logo", status:"Approved", matches:47, tone:"orange", monitored:true },
  { name:"Symbol mark", type:"Logo", status:"Approved", matches:28, tone:"black", monitored:true },
  { name:"Wordmark", type:"Logo", status:"Approved", matches:16, tone:"white", monitored:true },
  { name:"App icon", type:"Icon", status:"Approved", matches:12, tone:"peach", monitored:true },
  { name:"2024 horizontal logo", type:"Logo", status:"Retired", matches:4, tone:"gray", monitored:true },
  { name:"Campaign key visual", type:"Image", status:"Approved", matches:0, tone:"gradient", monitored:false },
];

const scansSeed = [
  { id:"SC-018", target:"brandyhq.com", type:"Scheduled", status:"Completed", pages:148, new:0, date:"Today, 9:30 AM", duration:"2m 18s" },
  { id:"SC-017", target:"Partner domains", type:"Scheduled", status:"Completed", pages:69, new:3, date:"Today, 6:00 AM", duration:"4m 02s" },
  { id:"SC-016", target:"brandfetch.com", type:"Manual", status:"Completed", pages:18, new:1, date:"Aug 10, 4:22 PM", duration:"42s" },
  { id:"SC-015", target:"saasframe.io", type:"Manual", status:"Completed", pages:9, new:1, date:"Aug 10, 12:10 PM", duration:"31s" },
  { id:"SC-014", target:"All monitored domains", type:"Scheduled", status:"Completed", pages:217, new:2, date:"Aug 9, 6:00 AM", duration:"6m 44s" },
];

function Badge({children,tone="gray"}){ return <span className={`badge ${tone}`}>{children}</span>; }
function Severity({value}){ return <span className={`severity ${value}`}><i/>{value}</span>; }
function Status({status}){ const map={new:["Needs review","amber"],reviewing:["Reviewing","blue"],approved:["Approved","green"],dismissed:["Dismissed","gray"],resolved:["Resolved","purple"]}; const item=map[status]||[status,"gray"]; return <Badge tone={item[1]}>{item[0]}</Badge>; }

function ProductRail(){
  return <aside className="product-rail" aria-label="Brandy product navigation">
    <div className="rail-top">
      <button className="brand-switcher" title="Change brand"><span>B</span><i className="bi bi-chevron-down"/></button>
      <button title="Collections"><i className="bi bi-collection"/></button>
      <button title="Brand checklist"><i className="bi bi-check2-square"/></button>
      <button title="Insights"><i className="bi bi-bar-chart"/></button>
      <button className="active" title="Brand Police"><i className="bi bi-shield-check"/><b>3</b></button>
    </div>
    <div className="rail-bottom">
      <button title="Brandy AI"><i className="bi bi-stars"/></button>
      <button title="Search"><i className="bi bi-search"/></button>
      <button title="Settings"><i className="bi bi-gear"/></button>
      <button className="avatar" title="Akshay Kumar">AK</button>
    </div>
  </aside>;
}

function Header({active,onNavigate}){
  return <><header className="page-header"><div className="feature-title"><strong>Brand Police</strong><Badge tone="soft">Beta</Badge></div><div className="header-actions"><button className="icon-button" title="Notifications"><i className="bi bi-bell"/><b/></button><button className={`icon-button ${active==="settings"?"active":""}`} title="Settings" onClick={()=>onNavigate("settings")}><i className="bi bi-gear"/></button>{active!=="scans"&&<button className="primary" onClick={()=>onNavigate("scans")}><i className="bi bi-plus"/>New scan</button>}</div></header><nav className="feature-tabs" aria-label="Brand Police sections">{navigation.map(([label,id,count])=><button key={id} className={active===id?"active":""} onClick={()=>onNavigate(id)}><span>{label}</span>{count?<b>{count}</b>:null}</button>)}</nav></>;
}

function PageTitle({title,description,children}){ return <div className="title-row"><div><h1>{title}</h1><p>{description}</p></div>{children}</div>; }
function Metric({label,value,change,icon,tone,onClick}){ return <button className="metric" onClick={onClick}><span className={`metric-icon ${tone}`}><i className={`bi ${icon}`}/></span><small>{label}</small><strong>{value}</strong><em>{change}</em></button>; }
function SourceCell({finding}){ return <div className="source-cell"><span className={`source-thumb ${finding.tone}`}>b</span><span><strong>{finding.page}</strong><small>{finding.domain} · {finding.id}</small></span></div>; }

function TrendChart(){ return <div className="trend-chart"><div className="chart-labels"><span>100</span><span>75</span><span>50</span></div><div className="chart-grid"><i/><i/><i/><svg viewBox="0 0 700 150" preserveAspectRatio="none"><defs><linearGradient id="score-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#424242" stopOpacity=".12"/><stop offset="1" stopColor="#424242" stopOpacity="0"/></linearGradient></defs><path d="M0,118 C75,112 92,92 155,99 S250,86 310,76 S410,83 470,54 S580,61 700,26 L700,150 L0,150 Z" fill="url(#score-fill)"/><path d="M0,118 C75,112 92,92 155,99 S250,86 310,76 S410,83 470,54 S580,61 700,26" fill="none" stroke="#424242" strokeWidth="2"/></svg></div><div className="chart-days"><span>Aug 5</span><span>Aug 6</span><span>Aug 7</span><span>Aug 8</span><span>Aug 9</span><span>Aug 10</span><span>Today</span></div></div>; }

function Overview({findings,onNavigate,onOpen}){
  const urgent=findings.filter(x=>x.status==="new").slice(0,3);
  return <div className="page-content"><PageTitle title="Brand Police" description="Find incorrect or unauthorised brand usage, review the evidence, and resolve it."><div className="scan-meta"><span className="live-dot"/><span><small>Monitoring active</small><strong>Last checked 12 minutes ago</strong></span></div></PageTitle>
    <section className="monitoring-summary panel"><div className="monitoring-copy"><span className="monitoring-icon"><i className="bi bi-shield-check"/></span><div><Badge tone="green">Monitoring active</Badge><h2>Your brand is being monitored</h2><p>Brand Police checks 4 domains and 5 approved assets. Three new findings need review.</p></div></div><div className="monitoring-facts"><span><strong>84%</strong><small>Brand health</small></span><span><strong>217</strong><small>Pages checked</small></span><span><strong>{findings.filter(x=>x.status==="new").length}</strong><small>Needs review</small></span></div><button className="primary" onClick={()=>onNavigate("findings")}>Review findings</button></section>
    <div className="overview-grid native-overview"><section className="panel urgent-panel"><div className="panel-heading"><div><h2>Needs your attention</h2><p>New findings ordered by severity</p></div><button className="text-button" onClick={()=>onNavigate("findings")}>View all <i className="bi bi-arrow-right"/></button></div><div className="table-scroll"><table><thead><tr><th>Finding</th><th>Issue</th><th>Severity</th><th>Last seen</th><th/></tr></thead><tbody>{urgent.map(f=><tr key={f.id} onClick={()=>onOpen(f)}><td><SourceCell finding={f}/></td><td>{f.issue}</td><td><Severity value={f.severity}/></td><td className="muted">{f.lastSeen}</td><td><i className="bi bi-chevron-right muted"/></td></tr>)}</tbody></table></div></section><section className="panel activity-panel"><div className="panel-heading"><div><h2>Recent activity</h2><p>Latest changes</p></div></div><div className="activity-list"><div><span className="activity-icon red"><i className="bi bi-flag"/></span><p><strong>High severity finding detected</strong><small>brandfetch.com · 12 min ago</small></p></div><div><span className="activity-icon green"><i className="bi bi-check2"/></span><p><strong>Violation marked resolved</strong><small>designmodo.com · Yesterday</small></p></div><div><span className="activity-icon gray"><i className="bi bi-radar"/></span><p><strong>Scheduled scan completed</strong><small>248 pages checked · Aug 9</small></p></div></div></section></div>
    <section className="quick-actions"><button onClick={()=>onNavigate("scans")}><i className="bi bi-search"/><span><strong>Scan a website</strong><small>Check a domain, sitemap, or URL</small></span><i className="bi bi-arrow-right"/></button><button onClick={()=>onNavigate("upload")}><i className="bi bi-cloud-arrow-up"/><span><strong>Check a creative</strong><small>Review a file before publishing</small></span><i className="bi bi-arrow-right"/></button><button onClick={()=>onNavigate("rules")}><i className="bi bi-journal-check"/><span><strong>Manage rules</strong><small>Choose what Brand Police checks</small></span><i className="bi bi-arrow-right"/></button></section>
  </div>;
}

function Findings({findings,onOpen,onUpdate}){
  const [query,setQuery]=useState(""); const [status,setStatus]=useState("all"); const [severity,setSeverity]=useState("all"); const [selected,setSelected]=useState([]);
  const filtered=useMemo(()=>findings.filter(f=>(status==="all"||f.status===status)&&(severity==="all"||f.severity===severity)&&`${f.page} ${f.domain} ${f.asset} ${f.issue}`.toLowerCase().includes(query.toLowerCase())),[findings,query,status,severity]);
  const toggle=id=>setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);
  const bulk=statusValue=>{selected.forEach(id=>onUpdate(id,{status:statusValue}));setSelected([]);};
  return <div className="page-content"><PageTitle title="Findings" description="Review detected brand usage and move every issue to resolution."><button className="secondary"><i className="bi bi-download"/>Export</button></PageTitle>
    <div className="saved-views"><button className="active">All findings <b>{findings.length}</b></button><button>Needs review <b>{findings.filter(x=>x.status==="new").length}</b></button><button>Assigned to me <b>2</b></button><button>High severity <b>2</b></button><button><i className="bi bi-plus"/>Save view</button></div>
    <section className="panel findings-panel"><div className="toolbar"><label className="search"><i className="bi bi-search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search findings, domains or assets"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="new">Needs review</option><option value="reviewing">Reviewing</option><option value="approved">Approved</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select><select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="all">All severity</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><span className="result-count">{filtered.length} findings</span></div>
      {selected.length>0&&<div className="bulk-bar"><strong>{selected.length} selected</strong><button onClick={()=>bulk("reviewing")}>Assign to me</button><button onClick={()=>bulk("approved")}>Approve use</button><button onClick={()=>bulk("resolved")}>Mark resolved</button><button onClick={()=>setSelected([])}><i className="bi bi-x"/></button></div>}
      <div className="table-scroll"><table className="findings-table"><thead><tr><th className="checkbox-cell"><input type="checkbox" checked={selected.length===filtered.length&&filtered.length>0} onChange={()=>setSelected(selected.length===filtered.length?[]:filtered.map(x=>x.id))}/></th><th>Finding</th><th>Issue</th><th>Severity</th><th>Status</th><th>Owner</th><th>Last seen</th><th/></tr></thead><tbody>{filtered.map(f=><tr key={f.id} onClick={()=>onOpen(f)}><td className="checkbox-cell" onClick={e=>e.stopPropagation()}><input type="checkbox" checked={selected.includes(f.id)} onChange={()=>toggle(f.id)}/></td><td><SourceCell finding={f}/></td><td><span className="issue-cell"><strong>{f.issue}</strong><small>{f.asset} · {f.match}</small></span></td><td><Severity value={f.severity}/></td><td><Status status={f.status}/></td><td>{f.owner}</td><td className="muted">{f.lastSeen}</td><td><i className="bi bi-chevron-right muted"/></td></tr>)}</tbody></table></div>
      {filtered.length===0&&<div className="empty"><i className="bi bi-search"/><strong>No findings match these filters</strong><button onClick={()=>{setQuery("");setStatus("all");setSeverity("all");}}>Clear filters</button></div>}<footer className="table-footer"><span>Showing {filtered.length} of {findings.length}</span><span>Page 1 of 1</span></footer>
    </section></div>;
}

function FindingDrawer({finding,onClose,onUpdate}){
  const [comment,setComment]=useState(""); const [notes,setNotes]=useState([]); if(!finding)return null; const act=status=>onUpdate(finding.id,{status});
  return <div className="drawer-layer"><button className="drawer-backdrop" onClick={onClose} aria-label="Close finding"/><aside className="drawer"><header><div><small>{finding.id}</small><h2>{finding.issue}</h2></div><button onClick={onClose}><i className="bi bi-x-lg"/></button></header><div className="drawer-body">
    <div className="evidence"><div className={`mock-page ${finding.tone}`}><div className="browser-bar"><i/><i/><i/><span>{finding.domain}</span></div><div className="mock-content"><span>BRAND</span><strong>b Brandy</strong><div className="detection-box"><b>Detected asset</b></div></div></div><div className="evidence-meta"><span><i className="bi bi-camera"/> Captured {finding.lastSeen}</span><a href={finding.url} target="_blank" rel="noreferrer">Open source <i className="bi bi-box-arrow-up-right"/></a></div></div>
    <section className="detail-section"><div className="detail-head"><h3>Assessment</h3><Severity value={finding.severity}/></div><p>{finding.context}</p><div className="confidence"><span><strong>{finding.confidence}%</strong> match confidence</span><div><i style={{width:`${finding.confidence}%`}}/></div></div></section>
    <section className="rule-callout"><i className="bi bi-journal-check"/><div><small>RELATED BRAND RULE</small><strong>{finding.rule}</strong></div></section>
    <section className="detail-section"><h3>Finding details</h3><dl><div><dt>Status</dt><dd><Status status={finding.status}/></dd></div><div><dt>Matched asset</dt><dd>{finding.asset}</dd></div><div><dt>First seen</dt><dd>{finding.firstSeen}</dd></div><div><dt>Owner</dt><dd><select value={finding.owner} onChange={e=>onUpdate(finding.id,{owner:e.target.value})}><option>Unassigned</option><option>Akshay Kumar</option><option>Himanshi</option></select></dd></div></dl></section>
    <section className="detail-section"><h3>Activity</h3><div className="notes">{notes.map((n,i)=><div key={i}><span>AK</span><p><strong>Akshay Kumar</strong><small>Just now</small>{n}</p></div>)}<div><span className="system-avatar"><i className="bi bi-shield-check"/></span><p><strong>Brand Police</strong><small>{finding.firstSeen}</small>Finding created from a scheduled scan.</p></div></div><div className="comment-box"><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add a comment"/><button disabled={!comment.trim()} onClick={()=>{setNotes([...notes,comment]);setComment("");}}><i className="bi bi-send"/></button></div></section>
  </div><footer><button className="secondary" onClick={()=>act("dismissed")}>Dismiss</button><button className="secondary" onClick={()=>act("approved")}>Approve use</button><button className="primary" onClick={()=>act(finding.status==="resolved"?"reviewing":"resolved")}><i className="bi bi-check2-circle"/>{finding.status==="resolved"?"Reopen":"Mark resolved"}</button></footer></aside></div>;
}

function Scans({onRun}){
  const [showNew,setShowNew]=useState(false); const [target,setTarget]=useState("domain"); const [url,setUrl]=useState("https://"); const [running,setRunning]=useState(false); const [done,setDone]=useState(null);
  const submit=async()=>{setRunning(true);const result=await onRun({target,url,assets:["Primary logo","Symbol mark"]});setDone(result);setRunning(false);};
  return <div className="page-content"><PageTitle title="Scans" description="Run one-time checks, schedule monitoring, and compare changes over time."><button className="primary" onClick={()=>setShowNew(true)}><i className="bi bi-radar"/>New scan</button></PageTitle>
    <section className="scan-summary"><div><span className="metric-icon orange"><i className="bi bi-radar"/></span><p><strong>Daily monitoring is active</strong><small>Next scan today at 6:00 PM · 4 domains · 5 assets</small></p><button className="secondary">Edit schedule</button></div><div className="scan-stats"><span><strong>23</strong><small>Scans this month</small></span><span><strong>1,842</strong><small>Pages checked</small></span><span><strong>7</strong><small>New findings</small></span><span><strong>98.6%</strong><small>Successful scans</small></span></div></section>
    <section className="panel"><div className="panel-heading"><div><h2>Scan history</h2><p>Previous monitoring runs</p></div><select><option>All scans</option><option>Scheduled</option><option>Manual</option></select></div><div className="table-scroll"><table><thead><tr><th>Scan</th><th>Target</th><th>Type</th><th>Status</th><th>Pages</th><th>New findings</th><th>Started</th><th>Duration</th></tr></thead><tbody>{scansSeed.map(s=><tr key={s.id}><td><strong>{s.id}</strong></td><td>{s.target}</td><td>{s.type}</td><td><Badge tone="green"><i className="bi bi-check2"/> {s.status}</Badge></td><td>{s.pages}</td><td>{s.new? <Badge tone="amber">{s.new} new</Badge>:"0"}</td><td className="muted">{s.date}</td><td className="muted">{s.duration}</td></tr>)}</tbody></table></div></section>
    {showNew&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setShowNew(false)}/><div className="modal wide"><header><div><h2>Start a new scan</h2><p>Choose what Brand Police should check</p></div><button onClick={()=>setShowNew(false)}><i className="bi bi-x-lg"/></button></header>{done?<div className="success-state compact"><span><i className="bi bi-check2"/></span><h2>Scan queued</h2><p>{done.pages} pages will be checked. The demo found {done.newFindings} potential matches.</p></div>:<div className="modal-body"><div className="choice-grid">{[["domain","bi-globe2","Full domain"],["sitemap","bi-diagram-3","Sitemap"],["url","bi-file-earmark","Single URL"]].map(([id,icon,label])=><button key={id} className={target===id?"selected":""} onClick={()=>setTarget(id)}><i className={`bi ${icon}`}/><strong>{label}</strong><small>{id==="domain"?"Crawl all public pages":id==="sitemap"?"Use an XML sitemap":"Check one exact page"}</small></button>)}</div><label className="field"><span>URL</span><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com"/></label><div className="option-row"><span><strong>Check all monitored assets</strong><small>5 active assets will be included</small></span><input type="checkbox" defaultChecked/></div><div className="option-row"><span><strong>Capture evidence screenshots</strong><small>Save a timestamped screenshot with each finding</small></span><input type="checkbox" defaultChecked/></div></div>}<footer>{done?<button className="primary" onClick={()=>{setDone(null);setShowNew(false);}}>Done</button>:<><button className="secondary" onClick={()=>setShowNew(false)}>Cancel</button><button className="primary" disabled={running||url.length<9} onClick={submit}><i className={`bi ${running?"bi-arrow-repeat spinning":"bi-radar"}`}/>{running?"Starting":"Start scan"}</button></>}</footer></div></div>}
  </div>;
}

function UploadCheck(){
  const inputRef=useRef(null); const [file,setFile]=useState(null); const [checking,setChecking]=useState(false); const [result,setResult]=useState(null);
  const choose=f=>{if(f){setFile(f);setResult(null);}}; const check=()=>{setChecking(true);window.setTimeout(()=>{setChecking(false);setResult({score:76,issues:[{title:"Incorrect logo color",severity:"High",rule:"Approved brand colors"},{title:"Clear space below minimum",severity:"Medium",rule:"Minimum clear space"},{title:"Headline uses unapproved terminology",severity:"Medium",rule:"Approved terminology"}]});},1100);};
  return <div className="page-content narrow"><PageTitle title="Upload check" description="Review creative work against your brand rules before it goes live."/><section className="upload-layout"><div className="panel upload-panel">{!file?<button className="drop-zone" onClick={()=>inputRef.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0]);}}><span><i className="bi bi-cloud-arrow-up"/></span><strong>Drop a file here or choose from your computer</strong><small>PNG, JPG, PDF, PPTX up to 50 MB</small><em>Choose file</em></button>:<div className="file-ready"><div className="file-preview"><i className="bi bi-file-earmark-image"/><span>CREATIVE<br/><b>Brandy</b></span></div><div className="file-meta"><span><strong>{file.name}</strong><small>{Math.max(1,Math.round(file.size/1024))} KB · Ready to check</small></span><button className="icon-button" onClick={()=>{setFile(null);setResult(null);}}><i className="bi bi-trash"/></button></div>{!result&&<button className="primary full" disabled={checking} onClick={check}><i className={`bi ${checking?"bi-arrow-repeat spinning":"bi-shield-check"}`}/>{checking?"Checking brand rules":"Check compliance"}</button>}</div>}<input ref={inputRef} type="file" hidden onChange={e=>choose(e.target.files?.[0])}/></div>
      <aside className="check-sidebar"><div className="check-info"><i className="bi bi-lightning-charge"/><h3>What gets checked</h3><ul><li>Logo version and proportions</li><li>Approved colors and contrast</li><li>Clear space and resolution</li><li>Typography and terminology</li></ul></div><div className="recent-checks"><h3>Recent checks</h3><button><span className="file-mini"><i className="bi bi-file-earmark-pdf"/></span><span><strong>Campaign concept.pdf</strong><small>92% · 2 issues</small></span></button><button><span className="file-mini"><i className="bi bi-image"/></span><span><strong>LinkedIn post.png</strong><small>100% · Passed</small></span></button></div></aside>
    </section>{result&&<section className="panel check-result"><div className="result-score"><span style={{"--score":`${result.score*3.6}deg`}}><strong>{result.score}</strong><small>/100</small></span><div><Badge tone="amber">Needs changes</Badge><h2>3 brand issues found</h2><p>Resolve the high severity issue before publishing.</p></div><button className="secondary"><i className="bi bi-download"/>Download report</button></div><div className="result-issues">{result.issues.map((issue,i)=><article key={issue.title}><span>{i+1}</span><div><strong>{issue.title}</strong><small>Rule: {issue.rule}</small></div><Severity value={issue.severity.toLowerCase()}/><button className="icon-button"><i className="bi bi-chevron-right"/></button></article>)}</div></section>}
  </div>;
}

function Assets(){ const [assets,setAssets]=useState(assetsSeed); return <div className="page-content"><PageTitle title="Monitored assets" description="Choose the approved and retired Brand Space assets Brand Police should track."><button className="secondary"><i className="bi bi-plus"/>Add from Brand Space</button></PageTitle><div className="asset-summary"><span><strong>5 of 6</strong><small>assets monitored</small></span><span><strong>107</strong><small>matches found</small></span><span><strong>1</strong><small>retired asset detected</small></span></div><section className="asset-grid">{assets.map((a,i)=><article className="asset-card" key={a.name}><div className={`asset-canvas ${a.tone}`}><span>b</span>{a.status==="Retired"&&<Badge tone="red">Retired</Badge>}<button className="icon-button"><i className="bi bi-three-dots"/></button></div><div className="asset-card-body"><div><strong>{a.name}</strong><small>{a.type} · {a.matches} matches</small></div><label className="switch"><input type="checkbox" checked={a.monitored} onChange={()=>setAssets(x=>x.map((v,n)=>n===i?{...v,monitored:!v.monitored}:v))}/><i/></label></div></article>)}</section></div>; }

function Domains(){ const [domains,setDomains]=useState(domainsSeed); const [adding,setAdding]=useState(false); const [value,setValue]=useState(""); return <div className="page-content"><PageTitle title="Domains" description="Classify domains so approved use is separated from suspicious use."><button className="primary" onClick={()=>setAdding(true)}><i className="bi bi-plus"/>Add domain</button></PageTitle><section className="panel"><div className="toolbar"><label className="search"><i className="bi bi-search"/><input placeholder="Search domains"/></label><select><option>All classifications</option><option>Owned</option><option>Approved partner</option><option>Unknown</option></select><span className="result-count">{domains.length} domains</span></div><div className="table-scroll"><table><thead><tr><th>Domain</th><th>Classification</th><th>Status</th><th>Frequency</th><th>Pages</th><th>Open findings</th><th>Health</th><th/></tr></thead><tbody>{domains.map(d=><tr key={d.domain}><td><span className="domain-cell"><i className="bi bi-globe2"/><strong>{d.domain}</strong></span></td><td><Badge tone={d.type==="Owned"?"purple":d.type==="Approved partner"?"green":"amber"}>{d.type}</Badge></td><td><span className="monitoring"><i/> {d.status}</span></td><td>{d.frequency}</td><td>{d.pages}</td><td>{d.findings}</td><td><strong>{d.score}%</strong></td><td><button className="icon-button"><i className="bi bi-three-dots"/></button></td></tr>)}</tbody></table></div></section>{adding&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setAdding(false)}/><div className="modal"><header><h2>Add monitored domain</h2><button onClick={()=>setAdding(false)}><i className="bi bi-x-lg"/></button></header><div className="modal-body"><label className="field"><span>Domain</span><input value={value} onChange={e=>setValue(e.target.value)} placeholder="example.com"/></label><label className="field"><span>Classification</span><select><option>Owned</option><option>Approved partner</option><option>Unknown</option></select></label><label className="field"><span>Scan frequency</span><select><option>Daily</option><option>Weekly</option><option>Monthly</option></select></label></div><footer><button className="secondary" onClick={()=>setAdding(false)}>Cancel</button><button className="primary" onClick={()=>{if(value.trim())setDomains([...domains,{domain:value.trim(),type:"Unknown",status:"Monitoring",frequency:"Weekly",pages:0,findings:0,score:100}]);setAdding(false);setValue("");}}>Add domain</button></footer></div></div>}</div>; }

function Rules(){ const [rules,setRules]=useState(rulesSeed); const [tab,setTab]=useState("all"); const visible=rules.filter(r=>tab==="all"||r.category.toLowerCase()===tab); return <div className="page-content"><PageTitle title="Compliance rules" description="Turn your brand guidelines into checks Brand Police can apply."><button className="primary"><i className="bi bi-plus"/>Create rule</button></PageTitle><div className="rule-tabs">{["all","logo","color","layout","quality","voice"].map(x=><button className={tab===x?"active":""} key={x} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div><section className="rules-list">{visible.map(r=><article className="panel rule-card" key={r.id}><span className="rule-icon"><i className="bi bi-shield-check"/></span><span><strong>{r.title}</strong><small>{r.description}</small><em>{r.category} · {r.severity} severity</em></span><Badge tone={r.enabled?"green":"gray"}>{r.enabled?"Active":"Paused"}</Badge><label className="switch"><input type="checkbox" checked={r.enabled} onChange={()=>setRules(x=>x.map(v=>v.id===r.id?{...v,enabled:!v.enabled}:v))}/><i/></label><button className="icon-button"><i className="bi bi-three-dots"/></button></article>)}</section></div>; }

function Reports(){ return <div className="page-content"><PageTitle title="Reports" description="Track compliance across domains, assets, partners, and time."><div className="button-group"><button className="secondary"><i className="bi bi-calendar3"/>Last 30 days</button><button className="primary"><i className="bi bi-download"/>Export report</button></div></PageTitle><section className="metrics-grid report-metrics"><Metric label="Overall compliance" value="84%" change="Up 6%" icon="bi-graph-up" tone="orange"/><Metric label="Issues detected" value="27" change="Down 12%" icon="bi-flag" tone="red"/><Metric label="Resolution rate" value="78%" change="21 of 27 resolved" icon="bi-check2-circle" tone="green"/><Metric label="Average response" value="2.4d" change="0.8d faster" icon="bi-clock" tone="blue"/></section><div className="report-grid"><section className="panel report-chart"><div className="panel-heading"><div><h2>Compliance over time</h2><p>Weekly score and resolved issues</p></div></div><TrendChart/></section><section className="panel scorecard"><div className="panel-heading"><div><h2>Domain scorecard</h2><p>Lowest score first</p></div></div>{domainsSeed.slice().sort((a,b)=>a.score-b.score).map(d=><div className="score-row" key={d.domain}><span><strong>{d.domain}</strong><small>{d.findings} open findings</small></span><div><i style={{width:`${d.score}%`}}/></div><b>{d.score}%</b></div>)}</section></div><section className="panel report-table"><div className="panel-heading"><div><h2>Issues by rule</h2><p>Rules creating the most findings</p></div></div><div className="table-scroll"><table><thead><tr><th>Rule</th><th>Category</th><th>Detected</th><th>Resolved</th><th>Open</th><th>Resolution rate</th></tr></thead><tbody>{[["Current logo only","Logo",9,7],["Protect logo proportions","Logo",7,5],["Approved brand colors","Color",6,5],["Minimum clear space","Layout",5,4]].map(r=><tr key={r[0]}><td><strong>{r[0]}</strong></td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td>{r[2]-r[3]}</td><td>{Math.round(r[3]/r[2]*100)}%</td></tr>)}</tbody></table></div></section></div>; }

function Settings(){ const [email,setEmail]=useState(true); const [high,setHigh]=useState(true); return <div className="page-content narrow"><PageTitle title="Brand Police settings" description="Control monitoring, notifications, and evidence retention."/><section className="settings-stack"><div className="panel settings-card"><div><h2>Monitoring</h2><p>Set the default schedule for monitored domains.</p></div><label className="field"><span>Default scan frequency</span><select><option>Daily</option><option>Weekly</option><option>Monthly</option></select></label><div className="option-row"><span><strong>Only surface new or changed findings</strong><small>Keep unchanged matches in scan history</small></span><label className="switch"><input type="checkbox" defaultChecked/><i/></label></div></div><div className="panel settings-card"><div><h2>Notifications</h2><p>Choose when Brand Police should alert your team.</p></div><div className="option-row"><span><strong>Email notifications</strong><small>Send a summary when new findings are detected</small></span><label className="switch"><input type="checkbox" checked={email} onChange={()=>setEmail(!email)}/><i/></label></div><div className="option-row"><span><strong>High severity alerts</strong><small>Alert immediately for critical brand misuse</small></span><label className="switch"><input type="checkbox" checked={high} onChange={()=>setHigh(!high)}/><i/></label></div></div><div className="panel settings-card"><div><h2>Evidence retention</h2><p>Keep timestamped screenshots for audit and resolution.</p></div><label className="field"><span>Retention period</span><select><option>12 months</option><option>24 months</option><option>Indefinitely</option></select></label></div></section><div className="settings-footer"><button className="primary">Save changes</button></div></div>; }

function Toast({toast,onClose}){ if(!toast)return null; return <div className={`toast ${toast.tone||"success"}`}><i className={`bi ${toast.tone==="error"?"bi-exclamation-circle":"bi-check-circle"}`}/><span>{toast.message}</span><button onClick={onClose}><i className="bi bi-x"/></button></div>; }

export default function BrandPolicePage(){
  const [active,setActive]=useState("overview"); const [findings,setFindings]=useState([]); const [loading,setLoading]=useState(true); const [selectedId,setSelectedId]=useState(null); const [toast,setToast]=useState(null);
  useEffect(()=>{brandPoliceService.listFindings().then(r=>setFindings(r.findings)).catch(()=>setToast({tone:"error",message:"Findings could not be loaded."})).finally(()=>setLoading(false));},[]);
  const selected=findings.find(f=>f.id===selectedId); const navigate=id=>{setActive(id);window.scrollTo({top:0,behavior:"smooth"});};
  const update=async(id,patch)=>{const before=findings;setFindings(x=>x.map(f=>f.id===id?{...f,...patch}:f));try{await brandPoliceService.updateFinding(id,patch);setToast({message:"Finding updated."});}catch{setFindings(before);setToast({tone:"error",message:"That update could not be saved."});}};
  const run=async payload=>{try{return await brandPoliceService.runScan(payload);}catch{setToast({tone:"error",message:"The scan could not be started."});throw new Error();}};
  return <div className="app-shell"><div className="accent-glow"/><ProductRail/><div className="curved-workspace"><main className="workspace"><Header active={active} onNavigate={navigate}/>{loading?<div className="loading-screen"><i className="bi bi-arrow-repeat spinning"/>Loading Brand Police</div>:<>{active==="overview"&&<Overview findings={findings} onNavigate={navigate} onOpen={f=>setSelectedId(f.id)}/>} {active==="findings"&&<Findings findings={findings} onOpen={f=>setSelectedId(f.id)} onUpdate={update}/>} {active==="scans"&&<Scans onRun={run}/>} {active==="upload"&&<UploadCheck/>} {active==="assets"&&<Assets/>} {active==="domains"&&<Domains/>} {active==="rules"&&<Rules/>} {active==="reports"&&<Reports/>} {active==="settings"&&<Settings/>}</>}</main></div><FindingDrawer finding={selected} onClose={()=>setSelectedId(null)} onUpdate={update}/><Toast toast={toast} onClose={()=>setToast(null)}/></div>;
}
